image: ubuntu:18.04

build:
  stage: build
  script:
  - apt-get -qq update
  - echo Y | apt-get install apt-utils python-pip git
  - echo Y | apt-get install libgmp-dev libmpfr-dev libmpc-dev libppl-dev
  - pip install Cython --verbose --disable-pip-version-check
  - pip install git+https://github.com/aleaxit/gmpy
  - pip install cysignals --verbose --disable-pip-version-check
  - pip install . --verbose --no-index

test:
  stage: test
  script:
  - cd testsddd
  - python rundoctest.py
  - python setup.py build_ext --inplace
  - python -c "import testpplpy"
  - python setup2.py build_ext --inplace
  - python -c "import testpplpy2"
