build:
  image: ubuntu:18.04
  stage: build
  script:
  - apt-get -qq update
  - yes Y | apt-get install -V libgmp-dev libmpfr-dev
  - pip install Cython --verbose --disable-pip-version-check
  - pip install gmpy2==2.1.0a1 --verbose --disable-pip-version-check --no-binary ":all:"
  - pip install cysignals --verbose --disable-pip-version-check
  - pip install . --verbose --no-index

test:
  stage: test
  script:
  - cd tests
  - python rundoctest.py
  - python setup.py build_ext --inplace
  - python -c "import testpplpy"
  - python setup2.py build_ext --inplace
  - python -c "import testpplpy2"