build:
  image: ubuntu:18.04
  stage: build
  script:
  - apt-get -qq update
  - apt-get install apt-utils
  - yes Y | apt-get install -V npm
  - ls

test:
  stage: test
  script:
  - cd tests
  - python rundoctest.py
  - python setup.py build_ext --inplace
  - python -c "import testpplpy"
  - python setup2.py build_ext --inplace
  - python -c "import testpplpy2"