build:
  image: ubuntu:14.04
  stage: build
  script:
  - apt-get -qq update
  - yes Y | apt-get install -V libgmp-dev libmpfr-dev libmpc-dev libppl-dev

test:
  stage: test
  script:
  - cd tests
  - python rundoctest.py
  - python setup.py build_ext --inplace
  - python -c "import testpplpy"
  - python setup2.py build_ext --inplace
  - python -c "import testpplpy2"