image: ubuntu:16.04
before_script:
- apt-get -qq update
- apt-get install -y apt-utils git
- if [[ $PYTHON == "python3.6" ]]; then
      apt-get install -y software-properties-common python-software-properties;
      printf "\n" | add-apt-repository ppa:deadsnakes/ppa;
      apt-get -qq update;
  fi
- apt-get install -y libgmp-dev libmpfr-dev libmpc-dev libppl-dev
- apt-get install -y $PKGS
- $PYTHON -m pip install Cython --disable-pip-version-check
- $PYTHON -m pip install cysignals --disable-pip-version-check
- $PYTHON -m pip install git+https://github.com/aleaxit/gmpy
- $PYTHON -m pip install . --verbose --no-index

.template_script:
  script: &test_script
  - cd tests
  - $PYTHON rundoctest.py
  - $PYTHON setup.py build_ext --inplace
  - $PYTHON -c "import testpplpy"
  - $PYTHON setup2.py build_ext --inplace
  - $PYTHON -c "import testpplpy2"

python2.7:
  stage: test
  variables:
    PYTHON: python
    PKGS: python-pip
  script: *test_script

python3.5:
  stage: test
  variables:
    PYTHON: python3
    PKGS: python3-pip
  script: *test_script

python3.6:
  stage: test
  variables:
    PYTHON: python3.6
    PKGS: python3.6 python3.6-dev python3-pip
  script: *test_script

python2.7.osx:
  tags: [osx]
  variables:
    PYTHON: python
    PKGS: python-pip
  script: *test_script
